add_newline = true

# [character]
# disabled = true

[line_break]
disabled = false

[cmd_duration]
format = "[  $duration]($style) "

[ruby]
disabled = true

[golang]
symbol = "  "

[lua]
symbol = "  "
