#!/bin/sh

function zsh_add_plugin() {
    OS=$(uname -s)
    case "${OS}" in
        "Linux")
        DISTRO=$(sed -n 's/^NAME=\(.*\)/\1/p' </etc/os-release)
        case "${DISTRO}" in
            *Arch*) dir="/usr/share/zsh/plugins" ;;
        esac
        ;;
    "Darwin") 
        dir="$(brew --prefix)/share"
        ;;
    esac
	([ -f "${dir}/${1}/${1}.zsh" ] && source "${dir}/${1}/${1}.zsh") ||
	[ -f "${dir}/${1}/${1}.plugin.zsh" ] && source "${dir}/${1}/${1}.zsh"
}
