#!/bin/zsh

alias vim="nvim"
alias code="nvim" # hehe

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

alias cp="cp -v"
alias mv="mv -v"
alias rm="rm -v"
alias ls="ls -FG"
alias mkdir="mkdir -p"
