#!/bin/zsh

alias vim="nvim"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

if [[ "$OSTYPE" == "darwin"* ]]; then
  alias ls="ls -FG"
else
  alias ls="ls -F --color=auto"
fi
