["plugins/tmux-sensible"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tmux-sensible/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

["plugins/rose-pine"]
    type = "archive"
    url = "https://github.com/rose-pine/tmux/archive/main.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

["plugins/tmux-resurrect"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tmux-resurrect/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

["plugins/tmux-continuum"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tmux-continuum/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
